SHOW DATABASES;

USE P1;

CREATE TABLE DEPARTMENT(DEPTNO INT, DNAME VARCHAR(20), LOC VARCHAR(20));
INSERT INTO DEPARTMENT VALUES(10,"ACCOUNTION","NEW YORK"),(20,"RESEARCH","DALLAS"),(30,"SALES","CHICAGO"),(40,"OPERATIONS","BOSTON");
SELECT * FROM DEPARTMENT;


Q-1
SELECT D.ACTNO,D.CNAME,D.BNAME,D.AMOUNT,D.ADATE, C.CITY FROM DEPOSIT D JOIN CUSTOMERS C ON D.CNAME="ANIL";
SELECT * FROM CUSTOMERS;
SELECT * FROM DEPOSIT;

Q-2
SELECT D.CNAME,C.CITY,B.LOANNO FROM DEPOSIT D JOIN CUSTOMERS C ON D.CNAME=C.CNAME JOIN BORROW B ON C.CNAME=B.CNAME WHERE C.CITY="NAGPUR";
SELECT * FROM BORROW;

Q-3
SELECT C.CNAME,C.CITY FROM CUSTOMERS C JOIN DEPOSIT D ON D.CNAME=C.CNAME;

Q-4
SELECT E.NAME,D.DEPTNO,D.DNAME FROM EMPLOYEE1 E LEFT JOIN DEPARTMENT D ON E.DEPTNO=D.DEPTNO;

Q-5
SELECT DISTINCT E.JOB,D.LOC FROM EMPLOYEE1 E JOIN DEPARTMENT D ON E.DEPTNO=D.DEPTNO WHERE E.DEPTNO=30;

Q-6 - INCOMPLETE
SELECT E.NAME,D.DEPTNO,D.DNAME,D.LOC FROM EMPLOYEE1 E JOIN DEPARTMENT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC="NEW YORK";
SELECT * FROM EMPLOYEE1;

Q-7
SELECT E1.NAME "EMPLOYEE",E1.EMPNO "EMP#",E1.MGR "MGR#",E2.NAME "MANAGER" FROM EMPLOYEE1 E1 LEFT OUTER JOIN EMPLOYEE1 E2 ON E1.MGR=E2.EMPNO;

Q-8
SELECT A.NAME,A.HIREDATE FROM EMPLOYEE1 A JOIN EMPLOYEE1 B ON A.HIREDATE>B.HIREDATE WHERE B.NAME="SCOOT";