USE P1;

 SELECT * FROM DEPOSIT;
 
 Q-1
 SELECT SUM(AMOUNT) FROM DEPOSIT;
 
 Q-2
 SELECT SUM(AMOUNT)"VIRAR LOAN" FROM DEPOSIT WHERE BNAME = "VIRAR";
 
 Q-3
 SELECT MAX(AMOUNT)"MAX LOAN" FROM BORROW WHERE BNAME="VRCE";
 
 Q-4
 SELECT COUNT(CNAME) "TOTAL NO. OF CUSTOMERS" FROM CUSTOMERS;
 
 Q-5
 SELECT COUNT(DISTINCT CITY) "TOTAL NO. OF CUSTOMER'S" FROM CUSTOMERS;
 
 Q-6
 CREATE TABLE SUPPLIER AS SELECT * FROM EMPLOYEE;
 SELECT * FROM SUPPLIER;
 
 Q-7
CREATE TABLE SUP1 AS SELECT EMP_NO,EMP_NAME FROM EMPLOYEE;
SELECT * FROM SUP1;

Q-8
CREATE TABLE SUP2 AS SELECT * FROM EMPLOYEE WHERE EMP_NO=NULL; 
SELECT * FROM SUP2;

Q-9 - INCOMPLETE
INSERT INTO SUP2 (ACTNO) SELECT (EMP_NO) FROM EMPLOYEE WHERE EMP_NAME LIKE '_N__ '; 

Q-10
TRUNCATE TABLE SUP1; 

Q-11
DELETE FROM SUPPLIER WHERE EMP_NO=103;
SELECT * FROM SUPPLIER;

Q-12 - iNCOMPLETE
RENAME SUP2 TO SUP3; 

Q-13
a
Q-14
UPDATE EMPLOYEE SET DEPT_NO=10 WHERE EMP_NAME LIKE "_m%";

Q-15
UPDATE EMPLOYEE SET EMP_NAME="DARSHAN" WHERE EMP_NO=103;