SHOW DATABASES;

USE P1;

Q-1
SELECT SUM(AMOUNT) FROM DEPOSIT WHERE ADATE >'1-jan-96';
SELECT * FROM DEPOSIT;

Q-2
SELECT SUM(D.AMOUNT) FROM DEPOSIT D ,CUSTOMERS C WHERE C.CITY='NAGPUR' AND C.CNAME=D.CNAME;
SELECT * FROM CUSTOMERS;

Q-3
SELECT MAX(D.AMOUNT) FROM DEPOSIT D,CUSTOMERS C WHERE C.CITY='BOMBAY' AND C.CNAME=D.CNAME; 

Q-4
SELECT MAX(EMP_SAL) "MAXIMUM" ,MIN(EMP_SAL) "MINIMUM",SUM(EMP_SAL) "SUM", AVG(EMP_SAL) "AVERAGE" FROM EMPLOYEE;
SELECT * FROM EMPLOYEE;

Q-5
SELECT MAX(EMP_SAL)-MIN(EMP_SAL) "DIFFERENCE" FROM EMPLOYEE; 

Q-6
SELECT COUNT(EMP_NO) FROM EMPLOYEE; 

Q-7
SELECT AVG(EMP_SAL) FROM EMPLOYEE GROUP BY DEPT_NO; 

Q-8
SELECT DEPT_NO,SUM(EMP_SAL) FROM EMPLOYEE GROUP BY DEPT_NO; 

Q-9
SELECT AVG(EMP_SAL) FROM EMPLOYEE GROUP BY DEPT_NO HAVING AVG(EMP_SAL) > 2000;

Q-10
SELECT DEPT_NO,SUM(EMP_SAL) FROM EMPLOYEE GROUP BY DEPT_NO HAVING SUM(EMP_SAL) > 3000 ORDER BY SUM(EMP_SAL);

Q-11
SELECT D.BNAME FROM DEPOSIT D , BRANCH B WHERE D.BNAME = B.CNAME AND B.CITY='BOMBAY' GROUP BY D.BNAME HAVING SUM(D.AMOUNT) > 5000;
SELECT * FROM BRANCH;
SELECT * FROM DEPOSIT;
